admin/blueprint.py
from flask import Blueprint
from flask import render_template, request, redirect, url_for, flash
from app import db
from models import *


admin = Blueprint('admin', __name__, template_folder='templates')

@admin.route('/manage_election', methods = ['POST','GET'])
def manage_election():
    
    if request.method == 'POST':
        print("In POST")
        print()
        if request.form["button_manage"] == "button_add_election":
            print("In Post")
            title = request.form['title']
            description = request.form['description']
            start_date = request.form['start_date']
            end_date = request.form['end_date']
            status = "Open"
            elections = Elections(title, description, start_date,end_date,status)

            db.session.add(elections)
            db.session.commit()

            flash("Election added successfully.")
     
        if request.form["button_manage"] == "button_close":
            print("Inside close")
            if(request.form['status'] == "Close"):
                flash("Election already closed for: " + request.form['title'])
            else:
                election = Elections.query.get(request.form['title'])
                election.status = "Close"
                db.session.commit()
                flash("Election CLOSED for: " + request.form['title'])
            """
            title = request.form['title']
            description = request.form['desc']
            sdate = request.form['sdate']
            edate = request.form['edate']
            status = "Close"
            """
            
            
        if request.form["button_manage"] == "button_delete":
            election = Elections.query.get(request.form['title'])
            status = request.form['status']
            if(status == "Open"):
                flash(request.form['title'] + " NOT delete, election is still ongoing.")
            else:
            
                db.session.delete(election)
                db.session.commit()
                flash("Election for: " + request.form['title'] + " deleted successfully.")

        if request.form["button_manage"] == "button_decrypt":
            if(request.form['status'] == "Open" or request.form['status'] == 'Ended'):
                flash("Election have not ended for: " + request.form['title'] + ", you may not decrypt now.")
            else:
                print("do your code here")
                return redirect(url_for("adminDecrypt"))

    if request.method == 'GET':
        print("get")

    elections = Elections.query.all()
    parties = Party.query.all()
    election_areas = ElectionArea.query.all()
    
    return render_template("admin/manage_election.html", elections=elections, parties=parties,election_areas=election_areas)

@admin.route('/view_party')
def view_party():
    parties = Party.query.all()
    election_areas = ElectionArea.query.all()
    return render_template("admin/party.html", parties = parties, election_areas = election_areas)


@admin.route('/insert_party', methods = ['POST'])
def insert_party():
    if request.method == 'POST':
        title = request.form['title']
        username = request.form['username']
        password = request.form['password']
        participating = request.form.getlist('participating')
        party = Party(title, username, password)
        print("Printing participating election")
        print(participating)
        print(ElectionArea.query.get(title))
        for title in participating:
            
            print(title)
            election_area = ElectionArea.query.get(title)
            #election_area = ElectionArea.query.filter(id).first()
            print(type(election_area))
            party.participating.append(election_area)
     
        db.session.add(party)
        db.session.commit()

        flash("Party added successfully.")
        return redirect(url_for('admin.view_party'))


@admin.route('/update_party', methods = ['GET','POST'])
def update_party():
    if request.method == 'POST':
        print(request.form)
        title = request.form['title']
        print(title)
        #title = request.form['title']
        party = Party.query.get(title)
        print(party)
        if party is None:
            return "Party not found", 404
        party.username = request.form['username']
        party.password = request.form['password']
        party.participating = []
        participating = request.form.getlist('participating')
        print("Printing participating")
        print(participating)
        for title in participating:
            print("Hello")
            print("Printing title: " + title)
            election_area = ElectionArea.query.filter_by(title=title).first()
            party.participating.append(election_area)

        db.session.commit()

        flash("Party updated successfully.")
        return redirect(url_for('admin.view_party'))
    # Save the changes to the database
    db.session.commit()

    # Return a response to the user
    return "Party updated successfully"

@admin.route('/delete_party/<id>', methods = ['GET','POST'])
def delete_party(id):
    party = Party.query.get(id)
    db.session.delete(party)
    db.session.commit()
    flash("Party deleted successfully.")
    return redirect(url_for('admin.view_party'))


@admin.route('/view_election_area')
def view_election_area():
    election_areas = ElectionArea.query.all()
    return render_template("admin/election_area.html", election_areas = election_areas)


@admin.route('/insert_election_area', methods = ['POST'])
def insert_election_area():
    if request.method == 'POST':
        
        title = request.form['title']
        description = request.form['description']
        election_area = ElectionArea(title, description)

        db.session.add(election_area)
        db.session.commit()

        flash("Election area added successfully.")
        return redirect(url_for('admin.view_election_area'))


@admin.route('/update_election_area', methods = ['GET','POST'])
def update_election_area():
    if request.method == 'POST':
        election_area = ElectionArea.query.get(request.form['title'])
        
        print("PRintign election_are")
        print(election_area)
        #print("Trying to get id")
        #print(request.form['id'])
        #election_area.id = request.form['id']
        #election_area.title = request.form['title']
        #election_area.title = request.form['title']
        election_area.description = request.form['description']
        
        db.session.commit()

        flash("Election area updated successfully.")
        return redirect(url_for('admin.view_election_area'))


@admin.route('/delete_election_area/<title>', methods = ['GET','POST'])
def delete_election_area(title):
    election_area = ElectionArea.query.get(title)
    db.session.delete(election_area)
    db.session.commit()
    flash("Election area deleted successfully.")
    return redirect(url_for('admin.view_election_area'))

templates/addDistrictModal.html

{% extends 'partyDistrictCreate.html' %}
{% block Test %}


<!-- Modal -->
<form action="" method="POST" enctype="multipart/form-data">     
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Select District</h5>
          
            <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="window.location.href = '{{url_for('CreateDistrictProfile')}}'">
                <span aria-hidden="true">&times;</span>
            </button>
     
          
        </div>
        <div class="modal-body">
            <label><b>Party Name</b></label>
            <input name = "PartyName" value = "{{party}}" readonly>
            <br>
            <label><b>Contesting Zone</b></label>
            <select name = "districtName" id = "districtName" onchange ="create()" required>
                <option value="" selected disabled hidden>Choose here</option>
                {% for zone in zones %}
                    <option>{{zone}}</option>
                {% endfor %}
            </select>
            <br><br>
          

            <div id='smc' ></div>
            <div id="grc" ></div>
        </div>
        <div class="modal-footer">
            
            <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="window.location.href = '{{url_for('CreateDistrictProfile')}}'">Close</button>
         
          
          <button id = "submit_button" type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
</form> 

  <script>
    $(document).ready(function() {
        console.log("window is loaded");
        $("#exampleModal").modal("show");
        
    })

    function create()
        {
            selected = document.getElementById("districtName")
            if (selected.options[selected.selectedIndex].value.includes("SMC"))
            {
                //reset 
                const g = document.getElementById("grc");
                g.innerHTML= '';

                const e = document.getElementById("smc");
                e.innerHTML= '<h4>Candidate 1</h4><label><b>Name</b> &nbsp;</label><input class = "Candidate-NameInput" type ="text" placeholder ="Candidate 1" name = "Name[]"  id="a1" required>&nbsp;<label><b>NRIC</b>&nbsp;</label><input type ="text" class = "Candidate-NricInput" placeholder ="S1234567Z" name = "NRIC[]"  id="a2" required><br><br><label><b>Upload Image</b></label><input type="file" name = "img[]" id="a3" required /><span>Upload your jpeg/jpg image. Max size 50 MB</span><br><br>'
                //document.getElementById('smc').appendChild(e)
            }

            else if (selected.options[selected.selectedIndex].value.includes("GRC"))
            {
                const s = document.getElementById("smc");
                s.innerHTML = '';
                
                const e = document.getElementById("grc");
                e.innerHTML= '';
                for (let i =0; i < 5; i++) {
                    e.innerHTML = e.innerHTML + '<h4>Candidate ' + (i+1) +'</h4><label><b>Name</b>&nbsp;</label><input type ="text" class = "Candidate-NameInput" placeholder ="Candidate ' + (i+1) +'" name = "Name[]"  id="a' + (i+1) +'" required>&nbsp;<label><b>NRIC</b>&nbsp;</label><input type ="text" class = "Candidate-NricInput" placeholder ="S1234567Z" name = "NRIC[]"  id="a2" required ><br><br><label><b>Upload Image</b></label><input type="file" name = "img[]" id="a3" required/><span>Upload your jpeg/jpg image. Max size 50 MB</span><br><br>'
                }
            }

        }
</script>
{% endblock %}

templates/election-result-page-c-l-o-s-e-d.html
<!DOCTYPE html>
<html lang="english">
  <head>
    <title>Closed</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8" />
    <meta property="twitter:card" content="summary_large_image" />

    <style data-tag="reset-style-sheet">
      html {  line-height: 1.15;}body {  margin: 0;}* {  box-sizing: border-box;  border-width: 0;  border-style: solid;}p,li,ul,pre,div,h1,h2,h3,h4,h5,h6,figure,blockquote,figcaption {  margin: 0;  padding: 0;}button {  background-color: transparent;}button,input,optgroup,select,textarea {  font-family: inherit;  font-size: 100%;  line-height: 1.15;  margin: 0;}button,select {  text-transform: none;}button,[type="button"],[type="reset"],[type="submit"] {  -webkit-appearance: button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner {  border-style: none;  padding: 0;}button:-moz-focus,[type="button"]:-moz-focus,[type="reset"]:-moz-focus,[type="submit"]:-moz-focus {  outline: 1px dotted ButtonText;}a {  color: inherit;  text-decoration: inherit;}input {  padding: 2px 4px;}img {  display: block;}html { scroll-behavior: smooth  }
    </style>
    <style data-tag="default-style-sheet">
      html {
        font-family: Inter;
        font-size: 16px;
      }

      body {
        font-weight: 400;
        font-style:normal;
        text-decoration: none;
        text-transform: none;
        letter-spacing: normal;
        line-height: 1.15;
        color: var(--dl-color-gray-black);
        background-color: var(--dl-color-gray-white);

      }
    </style>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
      data-tag="font"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
      data-tag="font"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
      data-tag="font"
    />
    <link rel="stylesheet" href="./style.css" />
  </head>
  <body>
    <div>
      <link href="./election-result-page-c-l-o-s-e-d.css" rel="stylesheet" />

      <div class="election-result-page-c-l-o-s-e-d-container">
        <div
          class="election-result-page-c-l-o-s-e-d-election-result-page-c-l-o-s-e-d"
        >
          <div
            class="election-result-page-c-l-o-s-e-d-frame16desktopsiteheading"
          >
          <img
          src="/static/public/playground_assets/mainicon.png"
          style="height:90px; width:150px;"
        />
            <div class="election-result-page-c-l-o-s-e-d-pageitems">
              <span class="election-result-page-c-l-o-s-e-d-text02">
                <span>Elections Info</span>
              </span>
              <span class="election-result-page-c-l-o-s-e-d-text04">
                <span>Security</span>
              </span>
              <span class="election-result-page-c-l-o-s-e-d-text06">
                <span>Contact Us</span>
              </span>
              <span class="election-result-page-c-l-o-s-e-d-text08">
                <span>FAQ</span>
              </span>
              <div
                class="election-result-page-c-l-o-s-e-d-frame28cart-icon"
              ></div>
              <button
                class="election-result-page-c-l-o-s-e-d-frame03filled-button"
              >
                <span class="election-result-page-c-l-o-s-e-d-text10">
                  <a href="{{ url_for('logOut')}}">
                    Logout
                </a>
                </span>
              </button>
            </div>
          </div>
          <img
            src="public/playground_assets/svg25homeicon2667-8x.svg"
            alt="SVG25HomeIcon2667"
            class="election-result-page-c-l-o-s-e-d-s-v-g25home-icon"
          />
          <img
            src="public/playground_assets/rectangle142667-h0ik-900h.png"
            alt="Rectangle142667"
            class="election-result-page-c-l-o-s-e-d-rectangle14"
          />
          <span class="election-result-page-c-l-o-s-e-d-text12">
            <span>PARLIAMENTARY ELECTIONS RESULTS</span>
          </span>
          <span class="election-result-page-c-l-o-s-e-d-text14">
            <span>
              The election results are currently unavailable. Please try again
              later.
            </span>
          </span>
          <div class="election-result-page-c-l-o-s-e-d-login-button">
            <span class="election-result-page-c-l-o-s-e-d-text16">
              <span>
                <span>Back to Home</span>
                <br />
                <span></span>
              </span>
            </span>
          </div>
          <img
            src="public/playground_assets/svg17clockicon2668-e59v.svg"
            alt="SVG17ClockIcon2668"
            class="election-result-page-c-l-o-s-e-d-s-v-g17clock-icon"
          />
        </div>
      </div>
    </div>
  </body>
</html>

templates/election_view_votes.html
<!DOCTYPE html>
<html lang="english">
  <head>
    <title>View Election Votes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8" />
    <meta property="twitter:card" content="summary_large_image" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <style data-tag="reset-style-sheet">
      html {  line-height: 1.15;}body {  margin: 0;}* {  box-sizing: border-box;  border-width: 0;  border-style: solid;}p,li,ul,pre,div,h1,h2,h3,h4,h5,h6,figure,blockquote,figcaption {  margin: 0;  padding: 0;}button {  background-color: transparent;}button,input,optgroup,select,textarea {  font-family: inherit;  font-size: 100%;  line-height: 1.15;  margin: 0;}button,select {  text-transform: none;}button,[type="button"],[type="reset"],[type="submit"] {  -webkit-appearance: button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner {  border-style: none;  padding: 0;}button:-moz-focus,[type="button"]:-moz-focus,[type="reset"]:-moz-focus,[type="submit"]:-moz-focus {  outline: 1px dotted ButtonText;}a {  color: inherit;  text-decoration: inherit;}input {  padding: 2px 4px;}img {  display: block;}html { scroll-behavior: smooth  }
    </style>
    <style data-tag="default-style-sheet">
      html {
        font-family: Inter;
        font-size: 16px;
      }

      body {
        font-weight: 400;
        font-style:normal;
        text-decoration: none;
        text-transform: none;
        letter-spacing: normal;
        line-height: 1.15;
        color: var(--dl-color-gray-black);
        background-color: var(--dl-color-gray-white);

      }
    </style>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
      data-tag="font"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
      data-tag="font"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
      data-tag="font"
    />
    <link rel="stylesheet" href="/static/styles/style.css" />
  </head>
  <body>
    <div>
      <link href="/static/styles/election_view_votes.css" rel="stylesheet" />

      <div class="election-result-page-container">
        <div class="election-result-page-election-result-page">
          <div class="election-result-page-frame16desktopsiteheading">
            <img
            src="/static/public/playground_assets/mainicon.png"
            style="height:90px; width:150px;"
          />
            <div class="election-result-page-pageitems">
              <span class="election-result-page-text02">
                <span>Elections Info</span>
              </span>
              <span class="election-result-page-text04">
                <span>Security</span>
              </span>
              <span class="election-result-page-text06">
                <span>Contact Us</span>
              </span>
              <span class="election-result-page-text08"><span>FAQ</span></span>
              <div class="election-result-page-frame28cart-icon"></div>
              <button class="election-result-page-frame03filled-button">
                <span class="election-result-page-text10">
                  <a href="{{ url_for('logOut')}}">Logout</a>
                </span>
              </button>
            </div>
          </div>
          <img
            src="/static/public/playground_assets/svg25homeicon2627-30hl.svg"
            alt="SVG25HomeIcon2627"
            class="election-result-page-s-v-g25home-icon"
          />
          <img
            src="/static/public/playground_assets/rectangle142627-v5oj-900h.png"
            alt="Rectangle142627"
            class="election-result-page-rectangle14"
          />
          <span class="election-result-page-text12">
            <span>PARLIAMENTARY ELECTIONS RESULTS</span>
          </span>
          <div  class="web-voter-homepage-image2 container">
            <table class="table">
                <tr><th>Election area</th><th>Party</th><th>No. Of Votes</th></tr>
                {% for n in vote %}
                <tr><td>{{n[0]}}</td><td>{{n[1]}}</td><td>{{n[2]}}</td></tr>
                {% endfor %}
            </table>
          </div>
          
        </div>
      </div>
    </div>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %} Party {% endblock %}

{% block content %}

<div class="container" style="text-align: center">
    <form action="" method="">
    <Button type="submit" formaction="{{ url_for('admin.manage_election') }}" name="button_manage_election" style="background-color: #d35555; /* Black */
    border: none;
    color: white;
    padding: 16px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    transition-duration: 0.4s;
    cursor: pointer;" >Manage election </Button>
    <br>
    </form>
</div>
{% endblock %}


templates/login.html
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;700&display=swap" rel="stylesheet">
<title>{% block title %}{% endblock %}</title>

E-voting
</head>

<body>
<style>
	body {
		background-color: #EEEEEE;
		text-align: center;
		font-family: 'Roboto Slab', serif;
	}

	.loginLogo{
		/*background-image: url("static/element-04.png");*/
		min-height: 700px;
	/* Center and scale the image nicely */
		background-position: center;
		background-repeat: no-repeat;
		position: relative;
	}

	.topright {
		position: absolute;
		top: 20px;
		right: 20px;
		font-size: 50px;
	}

	.bottomright {
		position: absolute;
		bottom: 250px;
		right: 90px;
	}

	form{
			color:rgba(0,0,0,0.8);
			justify-content: center;
			align-items: center;

	}
	.form-inline {
			display: inline-block;
			flex-flow: row wrap;
			align-items: center;
		}

	input[type=text], input[type=password] {
		width: 100%;
		padding: 15px;
		margin: 5px 0 20px 0;
		border: none;
		border-radius: 30px;
		background: #EBE5D7;
	}

	::placeholder{
		font-weight: 700;
	}

	.form-inline button {
		padding: 15px;
		margin: 5px 0 15px 0;
		border-color: rgb(255, 255, 255);
		background: #3C3C3C;
		color: white;
		border-radius: 30px;
		font-weight: 700;
	}

	.form-inline button:hover {
		background: white;
		color: black;
	}
</style>

<div class="bottomright">
	{% with messages = get_flashed_messages() %} check if there's messages to be displayed 
		{% if messages %}
			{% for msg in messages %}
				<h1>{{msg}}</h1>
			{% endfor %}
		{% endif %}
	{% endwith %}
</div>
<div class="loginLogo">
<a href= "{{ url_for('newlogin') }}">test</a>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
	<div class="loginform">
	<form class="form-inline" action="#" method="POST">
	<input type="text" id="ID" placeholder="Username" name="username">	<br>	
	<input type="password" id = "pw" placeholder = "Password"  name="password">
	<select class="topright" name="type" onchange="isParty()" id="type">
		{% for profile in profiles %}
		<option value={{profile[0]}} id = "profileName" >{{profile[0]}}</option>
		{% endfor %}
	</select>

	<select name="party" id="party">
		<option>Thunder Party</option>
		<option>Mallet Party</option>
		<option>Sun Party</option>
		<option>Palm Tree Party</option>
		<option>Campass Party</option>
		<option>Audi Party</option>
		<option>Nokia Party</option>
		<option>Olympics Torch Party</option>
	</select>
	<br>
	<button type="submit" value="submit"> LOGIN </button>
	<br>
	</form>
</div>
</div>
<br><br>

<script>
	//Set Party Selector list as non visible as default
	document.getElementById("party").style.display = 'none';

	function isParty(){
		selected = document.getElementById("type")

		//if profile type selector is party
		if (selected.options[selected.selectedIndex].value == "party") {
			document.getElementById("party").style.display = 'inline-block';
		}

		//if profile type is not party
		else {
			document.getElementById("party").style.display = 'none';
		}
	}
</script>

</body>
</html>

templates/view-party-info.html
<!DOCTYPE html>
<html lang="english">
  <head>
    <title>View Party Info</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8" />
    <meta property="twitter:card" content="summary_large_image" />

    <style data-tag="reset-style-sheet">
      html {  line-height: 1.15;}body {  margin: 0;}* {  box-sizing: border-box;  border-width: 0;  border-style: solid;}p,li,ul,pre,div,h1,h2,h3,h4,h5,h6,figure,blockquote,figcaption {  margin: 0;  padding: 0;}button {  background-color: transparent;}button,input,optgroup,select,textarea {  font-family: inherit;  font-size: 100%;  line-height: 1.15;  margin: 0;}button,select {  text-transform: none;}button,[type="button"],[type="reset"],[type="submit"] {  -webkit-appearance: button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner {  border-style: none;  padding: 0;}button:-moz-focus,[type="button"]:-moz-focus,[type="reset"]:-moz-focus,[type="submit"]:-moz-focus {  outline: 1px dotted ButtonText;}a {  color: inherit;  text-decoration: inherit;}input {  padding: 2px 4px;}img {  display: block;}html { scroll-behavior: smooth  }
    </style>
    <style data-tag="default-style-sheet">
      html {
        font-family: Inter;
        font-size: 16px;
      }

      body {
        font-weight: 400;
        font-style:normal;
        text-decoration: none;
        text-transform: none;
        letter-spacing: normal;
        line-height: 1.15;
        color: var(--dl-color-gray-black);
        background-color: var(--dl-color-gray-white);

      }
    </style>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
      data-tag="font"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
      data-tag="font"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
      data-tag="font"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
      data-tag="font"
    />
    <link rel="stylesheet" href="/static/styles/style.css" />
  </head>
  <body>
    <div>
      <link href="/static/styles/view-candidate-info2.css" rel="stylesheet" />

      
        <div class="view-candidate-info-view-candidate-info">
          <div style="position: absolute;
          top: 50%;
          left: 50%;
          margin-right: -50%;
          transform: translate(-50%, -50%);">
          <form action="#" method="POST">
            <label>Select Party: </label>
            <select name="parties" id="parties">
              <option disabled selected value> -- select an option -- </option>
              {% for n in parties %}
              <option value="{{ n[0] }}">{{ n[0] }}</option>
              {% endfor %}
            </select>
            <button class="button" onclick="myFunction()">Search</button>
          </form>
        </div>
          <div class="view-candidate-info-frame16desktopsiteheading">
            <img
            src="/static/public/playground_assets/mainicon.png"
            style="height:90px; width:150px;"
          />
            <div class="view-candidate-info-pageitems">
              <span class="view-candidate-info-text02">
                <span>Elections Info</span>
              </span>
              <span class="view-candidate-info-text04">
                <span>Security</span>
              </span>
              <span class="view-candidate-info-text06">
                <span>Contact Us</span>
              </span>
              <span class="view-candidate-info-text08"><span>FAQ</span></span>
              <div class="view-candidate-info-frame28cart-icon"></div>
              <button class="view-candidate-info-frame03filled-button">
                <span class="view-candidate-info-text10">
                  <a href="{{ url_for('logOut')}}">Logout</a>
                </span>
              </button>
            </div>
          </div>
          
          <img
            src="/static/public/playground_assets/svg25homeicon5113-gfxa.svg"
            alt="SVG25HomeIcon5113"
            class="view-candidate-info-s-v-g25home-icon"
          />
          
          
          <div class="view-candidate-info-login-button1">
            <span class="view-candidate-info-text14">
              <span>
                <a href="{{ url_for('voter')}}">Home</a>
                <br />
                <span></span>
              </span>
            </span>
          </div>
          
          <span class="view-candidate-info-text21">
            <span>
              <span>Time of last login: 17 Dec 2022, 3:29pm (SGT)</span>
              <br />
              <span>IP Address: 192.168.1.2</span>
            </span>
          </span>
          <div class="view-candidate-info-text26">
            <span class="view-candidate-info-text27">
              <span>View Candidate Info: Electoral Division - {{ district }}</span>
            </span>
          </div>
          
          
      </div>
    </div>
    
  </body>
</html>